### PR TITLE
build(ffi): include the scard feature by default

### PR DESCRIPTION
**Pull request by CBenoit**
cc @TheBestTvarynka

### CODE REVIEW

**Review by TheBestTvarynka — APPROVED** [review]

**Comment by CBenoit** [comment]
@TheBestTvarynka Does enabling scard by default for the ffi crate sounds good to you, or should it stay an option?

Also, the CI is hitting more compilation issues such as:
```
   Compiling sspi v0.13.0 (/home/runner/work/sspi-rs/sspi-rs)
error[E0308]: arguments to this function are incorrect
   --> ffi/src/winscard/system_scard/context.rs:724:21
    |
724 |                     (self.api.SCardGetStatusChange)(
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
725 |                         self.h_context,
726 |                         timeout,
    |                         ------- expected `u64`, found `u32`
    |
note: expected `*mut ScardReaderState`, found `*mut ScardReaderStateA`
   --> ffi/src/winscard/system_scard/context.rs:727:25
    |
727 |                         states.as_mut_ptr(),
    |                         ^^^^^^^^^^^^^^^^^^^
    = note: expected raw pointer `*mut ScardReaderState`
               found raw pointer `*mut ScardReaderStateA`
help: you can convert a `u32` to a `u64`
    |
726 |                         timeout.into(),
    |                                +++++++
```

**Comment by TheBestTvarynka** [comment]
> Also, the CI is hitting more compilation issues such as:

Hm, got it. Let me fix it

**Review by rbstp — APPROVED** [review]

**Review by thenextman — APPROVED** [review]

**Comment by CBenoit** [comment]
@TheBestTvarynka I rebased on top of master

**Comment by CBenoit** [comment]
@TheBestTvarynka Looks like there are still a few compilation errors. Can you fix the problems directly on my branch?

**Comment by TheBestTvarynka** [comment]
Yes, give a few minutes

**Comment by TheBestTvarynka** [comment]
Finally, the CI is happy

**Pull request merged**
